<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Pengenalan Tipe data dan Variable”**

**Disusun Oleh :**

**Marvel Teja**

**2611532003**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Muhammad Galid Alvero**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur kehadirat Tuhan Yang Maha Esa atas segala rahmat dan karunia-Nya sehingga laporan praktikum Pemrograman Python dengan judul "INSTALASI VISUAL STUDIO CODE, PYTHON, DAN INTEGERASI GITHUB MENGGUNAKAN GIT" ini dapat diselesaikan dengan baik dan tepat waktu.

Laporan ini disusun untuk memenuhi tugas praktikum serta memperdalam pemahaman mengenai konsep dasar pemrograman Python, khususnya pada instalasi python dan visual studio code, serta integerasi dengan git menggunakan git.

Penyusun menyadari bahwa laporan ini masih memiliki kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi kesempurnaan laporan ini di masa mendatang. Semoga laporan ini dapat memberikan manfaat bagi pembaca.

Padang, 2026

Marvel Teja

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Seiring dengan perkembangan teknologi informasi yang pesat, penggunaan sistem terkomputerisasi dalam kegiatan transaksi jual beli telah menjadi kebutuhan penting di berbagai sektor usaha. Proses transaksi secara manual sering kali memakan waktu lebih lama dan memiliki risiko kesalahan perhitungan (human error) yang dapat merugikan pihak penjual maupun pembeli. Oleh karena itu, penerapakan program kasir yang mampu melakukan perhitungan otomatis sangat diperlukan untuk meningkatkan efisiensi dan akurasi pembayaran.Dalam dunia pemrograman, bahasa Python menjadi salah satu pilihan utama untuk membangun aplikasi sederhana hingga kompleks karena sintaksnya yang mudah dipahami, efisien, dan fleksibel. Salah satu fitur dasar namun krusial dalam pemrograman Python adalah struktur kontrol percabangan (if-else). Fitur ini memungkinkan program untuk mengambil keputusan secara otomatis berdasarkan kondisi tertentu, seperti memberikan potongan harga (diskon) apabila total belanjaan pelanggan memenuhi kriteria minimal transaksi.Berdasarkan permasalahan dan konsep tersebut, praktikum ini dilaksanakan untuk merancang dan mengimplementasikan sebuah Program Kasir dan Perhitungan Diskon Otomatis berbasis Python. Program ini dibuat tanpa modul tambahan untuk melatih pemahaman mendalam mengenai logika dasar komputer, pemrosesan variabel masukan (input), serta penerapan logika kondisi (if-else) dalam menyelesaikan kasus transaksi dunia nyata secara cepat dan tepat.

## 1.2 Tujuan
1. Memahami penggunaan fungsi masukan (input) dan keluaran (print) pada Python.
2. Menerapkan pengondisian (conditional statement) menggunakan struktur if-else.
3. Melakukan operasi aritmatika dasar untuk menghitung nilai diskon dan total pembayaran.

## 1.3 Manfaat
1. Memahami penerapan logika dasar Python, khususnya penggunaan fungsi input-output dan struktur percabangan if-else dalam menyelesaikan masalah.
2. Mempercepat proses perhitungan transaksi belanja serta meminimalisir risiko kesalahan hitung (human error) dalam penentuan diskon.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

1. Bahasa Pemrograman Python
Python merupakan bahasa pemrograman tingkat tinggi yang bersifat interpreted dan berfokus pada keterbacaan kode. Bahasa ini cocok untuk pemula karena struktur sintaksnya intuitif dan tidak memerlukan deklarasi variabel yang rumit.
2. Tipe data Numerik
Tipe data numerik pada python di bagi menjadi 3:
    a. Integer, Bilangan bulat tanpa mengandung desimal.
    b. Float, Bilangan pecahan yang mengandung angka di belakang koma.
    c. Complex, Bilangan kompleks yang terdiri dari bagian real dan bagian imajiner yang ditandai dengan huruf j, contohnya 100+3j.
3. Tipe data String
Jenis data yang digunakan untuk menyimpan dan mengolah data berbentuk teks, seperti huruf, kata, kalimat, atau simbol.
4. Tipe data Boolean
Tipe data yang hanya memiliki 2 nilai, yaitu True (Benar) dan False (Salah).
5. Syntax input()
Input berfungsi untuk menerima data dari pengguna.
6. Konstanta
Konstanta adalah suatu variabel yang nilainya bersifat tetap dan tidak boleh diubah selama program dijalankan. Python secara bawaan sebenarnya tidak memiliki mekanisme khusus untuk membuat konstanta sejati, karena semua variabel pada dasarnya dapat diubah nilainya. Namun, Python menyediakan modul typing dengan tipe Final yang dapat digunakan sebagai penanda (annotation) bahwa suatu variabel dimaksudkan untuk tidak diubah nilainya.

## 2.2 Kode Program

### 2.2.1 Program "Numerik_2611532003.py"

In [1]:
# Buat file  dengan nama Numerik_NIM.py
# nama variable ditambah 4 digit terakhir NIM contoh: a_5500
# Create a variable with numeric type value.
a_2003 = 100
print("The type of variable having value", a_2003, " is", type(a_2003))

# Create a variable with float value
b_2003 = 10.2345
print("The type of variable having value", b_2003, " is", type(b_2003))

# Create a variable with complex value
c_2003 = 100 + 3j
print("The type of variable having value", c_2003, " is", type(c_2003))


The type of variable having value 100  is <class 'int'>
The type of variable having value 10.2345  is <class 'float'>
The type of variable having value (100+3j)  is <class 'complex'>


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat variabel a_2003 dengan nilai 100 dan menampilkan tipe data dari variabel tersebut. Nilai 100 termasuk tipe data integer (int).
2. Bagian kedua berfungsi untuk membuat variabel b_2003 dengan nilai 10.2345 dan menampilkan tipe data dari variabel tersebut. Nilai tersebut termasuk tipe data float karena memiliki angka desimal.
3. Bagian ketiga berfungsi untuk membuat variabel c_2003 dengan nilai 100 + 3j dan menampilkan tipe data dari variabel tersebut. Nilai tersebut termasuk tipe data complex karena memiliki bagian bilangan imajiner yang ditandai dengan j.

### 2.2.2 Program "String_2611532003.py"

In [5]:
# Buat file dengan nama string_NIM.py
# nama variable ditambah 4 digit nim terakhir contoh: nama_1234
# ganti programnya dan data masing2
nama_2003 = "Marvel Teja"
jenis_kelamin_2003 = 'L'
alamat_2003 = """
    Jl. Kotomerapak no 16
    Kec. Padang barat
    Kota padang
"""
agama_2003 = 'Buddha'
print("Nama saya adalah: ", nama_2003)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2003)
print("Alamat saya adalah: ", alamat_2003)
print("Agama saya adalah: ", agama_2003)


Nama saya adalah:  Marvel Teja
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Jl. Kotomerapak no 16
    Kec. Padang barat
    Kota padang

Agama saya adalah:  Buddha


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat variabel nama_2003 yang menyimpan data berupa teks (string), yaitu nama "Marvel Teja".
2. Bagian kedua berfungsi untuk membuat variabel jenis_kelamin_2003 yang menyimpan karakter "L", yang menunjukkan jenis kelamin laki-laki.
3. Bagian ketiga berfungsi untuk membuat variabel alamat_2003 yang menyimpan data teks dalam beberapa baris (multiline string) menggunakan tanda petik tiga ("""). Data tersebut berisi alamat.
4. Bagian keempat berfungsi untuk membuat variabel agama_2003 yang menyimpan data berupa teks, yaitu "Buddha".
5. Bagian kelima berfungsi untuk menampilkan isi dari variabel nama_2003, jenis_kelamin_2003, alamat_2003, dan agama_2003 menggunakan fungsi print().

### 2.2.3 Program "Boolean_2611532003.py"

In [8]:
# Buat file dengan nama Boolean_NIM.py
# Nama variable dtambah 4 digit terakhir contoh: nilai_1234
# Deklarasi variable dengan tipe data boolean
is_lulus_2003 = True
is_cumlaude_2003 = True

# Mengisi Boolean
nilai_2003 = 85
batas_lulus_2003 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_2003 = nilai_2003 >= batas_lulus_2003 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_2003)
print("Apakah Lulus?:", status_kelulusan_2003)
if is_lulus_2003 and is_cumlaude_2003:
    print("Selamat, Anda lulus dengan predikat Cum Laude")


=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cum Laude


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat variabel is_lulus_2003 dan is_cumlaude_2003 dengan nilai True yang menunjukkan kondisi benar.
2. Bagian kedua berfungsi untuk membuat variabel nilai_2003 dengan nilai 85 dan batas_lulus_2003 dengan nilai 75 sebagai nilai minimum kelulusan.
3. Bagian ketiga berfungsi untuk membandingkan nilai_2003 dengan batas_lulus_2003. Karena 85 lebih besar atau sama dengan 75, maka status_kelulusan_2003 menghasilkan nilai True.
4. Bagian keempat berfungsi untuk menampilkan informasi nilai dan status kelulusan menggunakan fungsi print().
5. Bagian kelima menggunakan kondisi if dan operator and untuk memeriksa apakah mahasiswa lulus dan mendapatkan predikat Cum Laude. Karena kedua variabel bernilai True, program menampilkan pesan "Selamat, Anda lulus dengan predikat Cum Laude".

### 2.2.4 Program "Input_2611532003.py"

In [1]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama variable ditambah 4 digit nim terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_2003 = input('Masukkan nilai panjang: ')
lebar_2003 = input('Masukkan nilai lebar: ')
luas_2003 = int(panjang_2003) * int(lebar_2003)
print("Luas =", luas_2003)


Luas = 10000


**Penjelasan :**
1. Bagian pertama berfungsi untuk meminta pengguna memasukkan nilai panjang menggunakan fungsi input(), kemudian menyimpannya ke dalam variabel panjang_2003.
2. Bagian kedua berfungsi untuk meminta pengguna memasukkan nilai lebar menggunakan fungsi input(), kemudian menyimpannya ke dalam variabel lebar_2003.
3. Bagian ketiga berfungsi untuk menghitung luas persegi panjang dengan mengalikan nilai panjang dan lebar. Fungsi int() digunakan untuk mengubah input yang awalnya berupa teks menjadi bilangan bulat.
4. Bagian keempat berfungsi untuk menampilkan hasil perhitungan luas menggunakan fungsi print().

### 2.2.5 Program "Konstanta_2611532003.py"

In [2]:
# Buat nama dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variable ditambah 4 digit nim terakhir contoh: jari_1234

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2003 = float(input('Masukkan nilai jari jari: '))
luas_2003 = PI * jari_2003 *jari_2003
print("Luas lingkaran dengan jari jari %.2f adalah %.2f" % (jari_2003,luas_2003))


pi: 3.140000
Luas lingkaran dengan jari jari 7.00 adalah 153.86


**Penjelasan :**
1. Bagian pertama berfungsi untuk mengimpor Final dari modul typing dan menetapkan nilai konstanta PI sebesar 3.14.
2. Bagian kedua berfungsi untuk menampilkan nilai PI dengan format bilangan desimal.
3. Bagian ketiga berfungsi untuk meminta pengguna memasukkan nilai jari-jari lingkaran, kemudian mengubah input tersebut menjadi tipe data float dan menyimpannya dalam variabel jari_2003.
4. Bagian keempat berfungsi untuk menghitung luas lingkaran dengan menggunakan nilai PI dan jari-jari yang telah dimasukkan.
5. Bagian kelima berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan nilai jari-jari dan luas yang ditampilkan hingga dua angka di belakang koma.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa Python memiliki berbagai tipe data dan struktur dasar yang dapat digunakan untuk membuat program sederhana. Tipe data yang dipelajari meliputi integer, float, complex, string, dan boolean. Selain itu, praktikum juga memahami penggunaan variabel, operator perbandingan dan logika, percabangan if, serta fungsi input() dan print() untuk menerima dan menampilkan data.

Melalui program yang dibuat, dapat diketahui bahwa data yang dimasukkan oleh pengguna melalui input() perlu dikonversi ke tipe data yang sesuai sebelum digunakan dalam perhitungan. Praktikum juga menunjukkan penerapan Python dalam melakukan perhitungan sederhana, seperti menghitung luas persegi panjang dan luas lingkaran. Dengan demikian, praktikum ini membantu memahami konsep dasar pemrograman Python sebagai dasar untuk membuat program yang lebih kompleks.


---
## DAFTAR PUSTAKA

[1] Python Software Foundation. (2023). Python 3.11.9 documentation.

[2] Microsoft. (2024). Visual Studio Code Documentation. Diakses dari https://code.visualstudio.com/docs

[3] GitHub, Inc. (2024). GitHub Docs. Diakses dari https://docs.github.com